# Generated by Django 4.0.6 on 2022-08-20 03:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='som_anim_category',
            fields=[
                ('ca_id', models.AutoField(primary_key=True, serialize=False)),
                ('ca_name1', models.CharField(max_length=9)),
                ('ca_name2', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='som_anim_in_state',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('state_code', models.CharField(choices=[('DCS', '사망'), ('ADP', '입양'), ('ETC', '기타')], max_length=3)),
                ('state_regdate', models.DateTimeField(auto_now_add=True)),
                ('extra_field1', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='som_anim_post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='som_animal',
            fields=[
                ('anim_id', models.AutoField(primary_key=True, serialize=False)),
                ('anim_code', models.CharField(max_length=50, null=True)),
                ('anim_name', models.CharField(max_length=100)),
                ('anim_sex', models.CharField(choices=[('M', '수컷'), ('F', '암컷')], max_length=1)),
                ('anim_regdate', models.DateField(auto_now_add=True)),
                ('anim_weight', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('anim_age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('anim_found', models.CharField(max_length=100)),
                ('anim_neuter', models.CharField(choices=[('NE', '중성화'), ('IN', '비중성화')], max_length=2)),
                ('anim_img1', models.ImageField(upload_to=main.models.som_animal.get_file_path)),
                ('anim_img2', models.ImageField(blank=True, null=True, upload_to=main.models.som_animal.get_file_path)),
                ('anim_img3', models.ImageField(blank=True, null=True, upload_to=main.models.som_animal.get_file_path)),
                ('anim_img4', models.ImageField(blank=True, null=True, upload_to=main.models.som_animal.get_file_path)),
                ('anim_breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.som_anim_category')),
                ('anim_post_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.som_anim_post')),
                ('in_state_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.som_anim_in_state')),
                ('shelter_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='member.som_shelter_profile')),
            ],
        ),
        migrations.CreateModel(
            name='som_anim_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comm_date', models.DateTimeField(auto_now_add=True)),
                ('comm_content', models.TextField(blank=True)),
                ('mb_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.som_user_profile')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.som_anim_post')),
            ],
        ),
    ]
