# Generated by Django 4.0.6 on 2022-08-20 03:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import member.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='som_user_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mb_hp', models.CharField(max_length=20, null=True, unique=True)),
                ('mb_name', models.CharField(max_length=20, null=True)),
                ('mb_img', models.ImageField(default='imgs/default_user.png', upload_to=member.models.som_user_profile.get_file_path)),
                ('mb_nick', models.CharField(blank=True, max_length=50)),
                ('mb_account_type', models.CharField(choices=[('K', '카카오'), ('G', '구글'), ('N', '네이버'), ('S', '솜뭉')], max_length=1, validators=[django.core.validators.MinLengthValidator(1)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='som_shelter_profile',
            fields=[
                ('shelter_id', models.AutoField(primary_key=True, serialize=False)),
                ('shelter_name', models.CharField(max_length=50)),
                ('shelter_addr', models.CharField(blank=True, max_length=100, null=True)),
                ('shelter_hp', models.CharField(max_length=25)),
                ('shelter_link', models.CharField(blank=True, max_length=45, null=True)),
                ('shelter_img', models.ImageField(blank=True, default='imgs/default_shelter.png', null=True, upload_to='imgs/shelter')),
                ('shelter_valid', models.CharField(choices=[('A', '활동'), ('P', '승인 대기 중'), ('Q', '탈퇴'), ('B', '차단')], default='P', max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
